### ISSUE TITLE
Causes rollup-plugin-babel tests to fail on npm2

### ISSUE THREAD

**Issue by Rich-Harris** [developit/modify-babel-preset#1]
@developit Unfortunately it looks like there's a problem with module resolution on npm 2: https://travis-ci.org/rollup/rollup-plugin-babel/jobs/101442677. Not quite sure what exactly yet

**Comment by developit** [comment]
@Rich-Harris that build went from red to green, is this still an issue?

**Comment by Rich-Harris** [comment]
@developit Yes – I published a new release of babel-preset-es2015-rollup that reverted the changes, so that people's builds wouldn't break in the meantime. But it's on a branch, so when this issue is fixed it'll just be a case of killing that branch and publishing again

**Comment by developit** [comment]
@Rich-Harris Might be worth trying this again with the latest updates.  Also I ran into some things that seemed to be solved by using `peerDependencies`. Possible that was the issue. It relates to tracking `require()`'d modules from nested `require()`'d babel presets - it's difficult to determine where they could have come from at runtime because there are no names.

I should add, there are now projects using `modify-babel-preset` both [directly](https://github.com/bkonkle/babel-preset-es2015-loose) and in a [layered/nested configuration](https://github.com/developit/babel-preset-es2015-minimal-rollup).

**Comment by developit** [comment]
Closing since this has now been modified to play nicely with npm 2.
